let number: number = 10;
console.log("Is number == 10? I predict True.");
console.log(number === 10); 
console.log("Is number != 5? I predict True.");
console.log(number !== 5); 
console.log("Is number > 5? I predict True.");
console.log(number > 5); 
console.log("Is number < 20? I predict True.");
console.log(number < 20); 
console.log("Is number >= 10? I predict True.");
console.log(number >= 10); 
console.log("Is number <= 5? I predict False.");
console.log(number <= 5); 
console.log("Is number == 15? I predict False.");
console.log(number === 15); 

console.log("Is number != 10? I predict False.");
console.log(number !== 10); 
console.log("Is number < 5? I predict False.");
console.log(number < 5); 
console.log("Is number >= 20? I predict False.");
console.log(number >= 20);